### PR TITLE
Typescript version Ae token migration

### PR DESCRIPTION
**Pull request by VitalJeevanjot**
Currently Working:

- Import and load token holders database.
- Merkle Tree generation and methods.
- Correct hash generation.
- Database insertion of Tree and Non-Tree data.

### CODE REVIEW

**Comment by marc0olo** [comment]
nice! will take a look tomorrow, provide feedback and possible request some changes ;-)

**Comment by marc0olo** [comment]
@genievot if this is still a draft please mark it accordingly and request review when the PR is ready

**Comment by VitalJeevanjot** [comment]
@marc0olo 
- All the routes that were available in the old backend are now recreated available in this new backend.
- Get requests execute fine: `root`, `info`, `hash`, siblings`.
- Put requests also added carefully: `validate` & `migrate` can be tested by any volunteer and can report if it gets an unexpected result.
- Further changes can be done through the ENV file easily.

The new backend is designed to be easy to use or easy to plug with the existing front-end.

Note: For more testings, One should try to performing post requests through the new backend and share the results. The current logging system is console.log and trace and is mostly focused on error logging. There are some more logging lines that are at the end of the file and can be used accordingly. I will see in the future to add a more prominent logging system here after we can confirm that the backend can migrate...

Let me know if there is any other requirement to fulfill or modifications required.

Thank you.

**Comment by marc0olo** [comment]
I haven't reviewed but yet, but please make sure to meet all the requirements written in the issue: https://github.com/aeternity/aepp-token-migration-backend-nodejs/issues/1

how is the logic currently for the migration check? via database or via static contract call? I didn't like that logic in the old backend ;-)

also, the database should be initialized on startup **_in case the DB is empty_**.

**Comment by VitalJeevanjot** [comment]
- Migration check is from the **contract call**.
- Database will be initialized (If it is empty or the amount of the record is different).

**Comment by marc0olo** [comment]
@genievot I am definitely missing a meaningful README file here. I will probably have some other small change requests. we will see. but I need a README how to use the application. this is essential ;-)

btw here is the repo with the smart contracts and various tests regarding the migration. I assume these are accurate and can be used to locally verify if the migration backend works as expected. that's not necessarily a task for you. but maybe you want to check it out:
- https://github.com/aeternity/aepp-token-migration-smart-contract/blob/master/test/token-migration-tests.js

**Comment by VitalJeevanjot** [comment]
The Readme is added, Thank you for sharing the tests, I know you are working on them. I also check on those sooner if required.
Please let me know that if I can provide more information on this.

**Comment by marc0olo** [comment]
@genievot I just wanted to review and then noticed you were using mongodb instead of postgres. what's the reason for that? I expected this to be a postgres db like in the old backend

**Comment by marc0olo** [comment]
also, please make sure the JSON responses are the same like in the old migration app. I just compared the `/info/` endpoint and got following results:

## Old migration backend

```json
{
   "index":21015,
   "hash":"DEFFF0A9D69EA2272EA90DEF351E5B3D9AF2DF9C8E2AD67EE2467504201ABD73",
   "tokens":"1",
   "migrated":false,
   "migrateTxHash":""
}
```

## Your version

```json
{
   "hash":"DEFFF0A9D69EA2272EA90DEF351E5B3D9AF2DF9C8E2AD67EE2467504201ABD73",
   "eth_address":"0XFFFDAE92690664EFB196510953BDEF6650AAFF8F",
   "balance":"1",
   "leaf_index":21015,
   "migrated":false,
   "migrateTxHash":"th_"
}
```

the `migrationTxHash` should be empty of course if there has no migration happened

**Comment by VitalJeevanjot** [comment]
> @genievot I just wanted to review and then noticed you were using mongodb instead of postgres. what's the reason for that? I expected this to be a postgres db like in the old backend

I actually didn't found this in the description so I used which one is easier to set up and start with by anyone for anybody hosting this.

**Comment by VitalJeevanjot** [comment]
> also, please make sure the JSON responses are the same like in the old migration app. I just compared the `/info/` endpoint and got following results:
> 
> ## Old migration backend
> ```json
> {
>    "index":21015,
>    "hash":"DEFFF0A9D69EA2272EA90DEF351E5B3D9AF2DF9C8E2AD67EE2467504201ABD73",
>    "tokens":"1",
>    "migrated":false,
>    "migrateTxHash":""
> }
> ```
> 
> ## Your version
> ```json
> {
>    "hash":"DEFFF0A9D69EA2272EA90DEF351E5B3D9AF2DF9C8E2AD67EE2467504201ABD73",
>    "eth_address":"0XFFFDAE92690664EFB196510953BDEF6650AAFF8F",
>    "balance":"1",
>    "leaf_index":21015,
>    "migrated":false,
>    "migrateTxHash":"th_"
> }
> ```
> 
> the `migrationTxHash` should be empty of course if there has no migration happened

It looks like I took these references from the smart contract and request queries. You are right, I will rename the fields to match the original version.

**Comment by marc0olo** [comment]
can you update the README to fit to the postgres settings?

is mongoose still required as dependency?

**Pull request merged**
